---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: pr0d1r2/nix-lefthook-ci-action@fbeb9d9cfe38488df1ccfbe220179aa9390fb074
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  check-darwin:
    needs: check-linux
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: pr0d1r2/nix-lefthook-ci-action@fbeb9d9cfe38488df1ccfbe220179aa9390fb074
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  check-linux-arm:
    needs: check-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: pr0d1r2/nix-lefthook-ci-action@fbeb9d9cfe38488df1ccfbe220179aa9390fb074
        with:
          extra-platforms: aarch64-linux
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
